title: test
author: Karson Sommer
email: karson-sommer@uiowa.edu
description: > # this means to ignore newlines until "baseurl:"
  test

# social links
github_username:  karsonkevin2 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
